stages:
    - check
    - build

check:
    stage: check
    tags:
        - vs2019
        - windows10
    script:
        - cd Tools
        - pip install cmakelang
        - python format-cmake.py
        - python format-cpp.py

build:windows_debug:
    stage: build
    tags:
        - vs2019
        - windows10
    needs:
        - check
    script:
        - cd Tools
        - python build.py -t debug
    artifacts:
        expire_in: '4 weeks'
        paths:
            - build-x64-window-debug/bin/

build:windows_release:
    stage: build
    tags:
        - vs2019
        - windows10
    needs:
        - check
    script:
        - cd Tools
        - python build.py -t release
    artifacts:
        expire_in: '4 weeks'
        paths:
            - build-x64-window-release/bin/

build:linux_debug:
    stage: build
    tags:
        - gcc
    needs:
        - check
    script:
        - cd Tools
        - python build.py -t debug
    artifacts:
        expire_in: '4 weeks'
        paths:
            - build-x64-linux-debug/bin/

build:linux_release:
    stage: build
    tags:
        - gcc
    needs:
        - check
    script:
        - cd Tools
        - python build.py -t release
    artifacts:
        expire_in: '4 weeks'
        paths:
            - build-x64-linux-release/bin/


build_docs:
  stage: .post 
  script:
  - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/15800262/trigger/pipeline
